apiVersion: v1
kind: ConfigMap
metadata:
  name: homeport-files-config
data:
  {{ $fpath := "" }}
  {{ if .Values.waldur.whitelabeling.manifestJsonPath }}
    {{ $fpath = .Values.waldur.whitelabeling.manifestJsonPath }}
  manifest.json: |
{{ .Files.Get $fpath | indent 4 }}
  {{end}}

  {{ if .Values.waldur.whitelabeling.privacyHtmlPath }}
    {{ $fpath = .Values.waldur.whitelabeling.privacyHtmlPath }}
  privacy.html: |
{{ .Files.Get $fpath | indent 4 }}
  {{ end }}

  {{ if .Values.waldur.whitelabeling.tosHtmlPath }}
    {{ $fpath = .Values.waldur.whitelabeling.tosHtmlPath }}
  tos.html: |
{{ .Files.Get $fpath | indent 4 }}
  {{ end }}
