{{ if .Values.waldur.saml2.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: waldur-saml2-secret
type: Opaque
data:
{{ $certsDirTemp := .Values.waldur.saml2.dir | printf "%s/*" }}
{{ (.Files.Glob $certsDirTemp).AsSecrets | indent 2 }}
{{ end }}
